In [19]:
def lesser_of_two_evens(a,b):
    if a%2==0 and b%2==0:
      if a<b:
        print(a)
      else:
        print(b)
    else:
      if a>b:
        print(a)
      else:
        print(b)
# Check
lesser_of_two_evens(2,4)
# Check
lesser_of_two_evens(2,5)

2
5


In [26]:
def animal_crackers(text):
    words = text.split()
    print(words[0][0] == words[1][0])
# Chec
animal_crackers('Levelheaded Llama')
# Check
animal_crackers('Crazy Kangaroo')

True
False


MAKES TWENTY: Given two integers, return True if the sum of the integers is 20 or if one of the integers is 20. If not, return False
makes_twenty(20,10) --> True
makes_twenty(12,8) --> True
makes_twenty(2,3) --> False

In [29]:
def makes_twenty(n1,n2):
    if n1+n2==20 or n1==20 or n2==20:
      print("True")
    else:
      print("false")
# Check
makes_twenty(20,10)
# Check
makes_twenty(2,3)

True
True


OLD MACDONALD: Write a function that capitalizes the first and fourth letters of a name

old_macdonald('macdonald') --> MacDonald

In [43]:
def old_macdonald(name):
   result = name[0].upper() + name[1:3] + name[3].upper() + name[4:]
   print(result)
old_macdonald('macdonald')

MacDonald


MASTER YODA: Given a sentence, return a sentence with the words reversed
master_yoda('I am home') --> 'home am I'
master_yoda('We are ready') --> 'ready are We'
Note: The .join() method may be useful here. The .join() method allows you to join together strings in a list with some connector string. For example, some uses of the .join() method:

>>> "--".join(['a','b','c'])
>>> 'a--b--c'
This means if you had a list of words you wanted to turn back into a sentence, you could just join them with a single space string:

>>> " ".join(['Hello','world'])
>>> "Hello world

In [22]:
def master_yoda(text):
    words = text.split()
    reversed_words = []

    for word in words:
        #print(word)
        reversed_words.insert(0, word)  # Inserts each word at the beginning

    print(' '.join(reversed_words))

master_yoda("Python is fun")  # Output: "fun is Python"



fun is Python


ALMOST THERE: Given an integer n, return True if n is within 10 of either 100 or 200
almost_there(90) --> True
almost_there(104) --> True
almost_there(150) --> False
almost_there(209) --> True

In [39]:
def almost_there(n):
  if 90<=n<=110 or 190<=n<=210:
    print("true")
  else:
    print("false")

almost_there(196)
almost_there(108)

true
true


In [62]:
def has_33(nums):
    for i in range(len(nums)-1):
     if nums[i] ==3 and nums[i+1]==3:
      print("true")

has_33([1,2,3,3,5,6,4])


true


In [63]:
def paper_doll(text):
    result = ''
    for char in text:
      result = result + char*3
    print(result)
paper_doll("Hello")

HHHeeellllllooo


In [12]:
def blackjack(a,b,c):
  sum = a + b + c
  if sum<=21:
    return sum
  else:
    if a==11 or b==11 or c==11:
      sum = sum - 10
      return sum
    else :
      print("bust")
# Check
blackjack(9,9,11)

19

In [13]:
def spy_game(nums):
    code = [0, 0, 7]
    for num in nums:
        if num == code[0]:
            code.pop(0)
        if len(code) == 0:
            return True
    return False


The second assignment

st = 'Print only the words that start with s in this sentence'

In [8]:
st = 'Print only the words that start with s in this sentence'
i = st.split()
for num in i:
  if num[0]=='s':
    print(num)


start
s
sentence




Use range() to print all the even numbers from 0 to 10.

In [10]:
for num in range(0, 11, 2):
    print(num)


0
2
4
6
8
10


In [11]:
[num for num in range(1,51) if num%3==0]

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

st = 'Print every word in this sentence that has an even number of letters'

In [13]:
st = 'Print every word in this sentence that has an even number of letters'
i = st.split()
for num in i :
  if len(num)%2 == 0:
    print(num)

word
in
this
sentence
that
an
even
number
of


In [17]:
for num in range(1,101):
  if num%3 == 0:
    print("Fizz")
  if num%5 == 0:
    print("Buzz")
  if num%3 == 0 and num%5 == 0:
    print("FizzBuzz")
  else:
    print(num)

1
2
Fizz
3
4
Buzz
5
Fizz
6
7
8
Fizz
9
Buzz
10
11
Fizz
12
13
14
Fizz
Buzz
FizzBuzz
16
17
Fizz
18
19
Buzz
20
Fizz
21
22
23
Fizz
24
Buzz
25
26
Fizz
27
28
29
Fizz
Buzz
FizzBuzz
31
32
Fizz
33
34
Buzz
35
Fizz
36
37
38
Fizz
39
Buzz
40
41
Fizz
42
43
44
Fizz
Buzz
FizzBuzz
46
47
Fizz
48
49
Buzz
50
Fizz
51
52
53
Fizz
54
Buzz
55
56
Fizz
57
58
59
Fizz
Buzz
FizzBuzz
61
62
Fizz
63
64
Buzz
65
Fizz
66
67
68
Fizz
69
Buzz
70
71
Fizz
72
73
74
Fizz
Buzz
FizzBuzz
76
77
Fizz
78
79
Buzz
80
Fizz
81
82
83
Fizz
84
Buzz
85
86
Fizz
87
88
89
Fizz
Buzz
FizzBuzz
91
92
Fizz
93
94
Buzz
95
Fizz
96
97
98
Fizz
99
Buzz
100


In [ ]:
st = 'Create a list of the first letters of every word in this string'
first_letters = [word[0] for word in st.split()]
print(first_letters)


In [23]:
import numpy as np
arr = np.array([[1,2,4],[7,13,21]])

print(arr)
print("Shape:", arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape: (2, 3)


In [9]:
import numpy as np
n_rows = 2
n_columns = 3

x = np.random.randn(n_rows, n_columns)

print(x)


[[ 1.05652249  1.44306673 -1.15284467]
 [ 0.40007918 -1.03474051 -0.4409006 ]]


In [10]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
ZERO_ARR = np.zeros((4, 5, 2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR = np.ones((4, 5, 2))
# < END >

print(ONE_ARR)


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [12]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose = np.transpose(y)
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat = y.reshape(-1,1)
# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:

# Initialize the column matrix here
y = np.array([[4],
              [27],
              [11]])
#

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

#
y_new = np.array([[1, 2, 3],
              [4, 5, 6]])
# Multiply both the arrays here
z = np.dot(y_new,y)
#
assert z.shape == (2, 1)

print(z)

[[ 4]
 [27]
 [11]]
[[ 91]
 [217]]


In [2]:
import numpy as np
x = np.array([4, 1, 5, 6, 11])

#
# Create a new array y with the middle 3 elements of x
y = x[1:4]
#

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#
# Create a new array w with alternating elements of z
w = z[::2]
#

print(w)

[1 5 6]
[1 3 5 7 9]


In [3]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

#
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d = arr_2d[1:4, 1:]
#

print(sliced_arr_2d)


[[7 9]
 [4 5]
 [6 1]]


In [4]:
arr1 = np.array([1, 2, 3, 4])
b = 1

#
# Implement broadcasting to add b to each element of arr1
arr1 = arr1 + b
#

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

#
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2 = arr2 * arr3
#

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


In [ ]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
#



#

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
#

#

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_vectorized)

In [13]:
import pandas as pd
sal= pd.read_csv("C:\\Users\\ronak\\OneDrive\\Desktop\\Downloads\\archive\\Salaries.csv")
print(sal.head())

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ronak\\OneDrive\\Desktop\\Downloads\\archive\\Salaries.csv'