In [ ]:
import numpy as np
arr = np.array([[1,2,4],[7,13,21]])

print(arr)
print("Shape:", arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape: (2, 3)


In [ ]:
import numpy as np
n_rows = 2
n_columns = 3

x = np.random.randn(n_rows, n_columns)

print(x)


[[ 1.05652249  1.44306673 -1.15284467]
 [ 0.40007918 -1.03474051 -0.4409006 ]]


In [ ]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
ZERO_ARR = np.zeros((4, 5, 2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR = np.ones((4, 5, 2))
# < END >

print(ONE_ARR)


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose = np.transpose(y)
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat = y.reshape(-1,1)
# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:

# Initialize the column matrix here
y = np.array([[4],
              [27],
              [11]])
#

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

#
y_new = np.array([[1, 2, 3],
              [4, 5, 6]])
# Multiply both the arrays here
z = np.dot(y_new,y)
#
assert z.shape == (2, 1)

print(z)

[[ 4]
 [27]
 [11]]
[[ 91]
 [217]]


In [ ]:
import numpy as np
x = np.array([4, 1, 5, 6, 11])

#
# Create a new array y with the middle 3 elements of x
y = x[1:4]
#

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#
# Create a new array w with alternating elements of z
w = z[::2]
#

print(w)

[1 5 6]
[1 3 5 7 9]


In [ ]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

#
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d = arr_2d[1:4, 1:]
#

print(sliced_arr_2d)


[[7 9]
 [4 5]
 [6 1]]


In [ ]:
arr1 = np.array([1, 2, 3, 4])
b = 1

#
# Implement broadcasting to add b to each element of arr1
arr1 = arr1 + b
#

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

#
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2 = arr2 * arr3
#

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


In [ ]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
#



#

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
#

#

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_vectorized)